ce_liceo_paraiso_homepage:
    path:     /home
    defaults: { _controller: CELiceoParaisoBundle:Default:index }

ce_liceo_paraiso_description:
    path:     /description
    defaults: { _controller: CELiceoParaisoBundle:Default:showDescription }

ce_liceo_paraiso_objectives:
    path:     /objectives
    defaults: { _controller: CELiceoParaisoBundle:Default:showObjectives }
    
ce_liceo_paraiso_vision:
    path:     /vision
    defaults: { _controller: CELiceoParaisoBundle:Default:showVision }
    
ce_liceo_paraiso_mision:
    path:     /mision
    defaults: { _controller: CELiceoParaisoBundle:Default:showMision }
    
ce_liceo_paraiso_managers:
    path:     /information
    defaults: { _controller: CELiceoParaisoBundle:Default:showManagers }
    
ce_liceo_paraiso_gallery:
    path:     /gallery
    defaults: { _controller: CELiceoParaisoBundle:Default:showGallery }
    
ce_liceo_paraiso_vocational:
    path:     /vocational_area
    defaults: { _controller: CELiceoParaisoBundle:Area:showVocationalArea }

ce_liceo_paraiso_nocturnal:
    path:     /nocturnal_area
    defaults: { _controller: CELiceoParaisoBundle:Area:showNocturnalArea }

ce_liceo_paraiso_diurnal:
    path:     /diurnal_area
    defaults: { _controller: CELiceoParaisoBundle:Area:showDiurnalArea }
    
ce_liceo_paraiso_ubication:
    path:     /ubication
    defaults: { _controller: CELiceoParaisoBundle:Default:showUbication }
    
ce_liceo_paraiso_login:
    path:     /singup
    defaults: { _controller: CELiceoParaisoBundle:Administrator:login }